### ISSUE TITLE
Doesn't compile on latest DMD.

### ISSUE THREAD

**Issue by aberba** [clinei/3ddemo#1]
This code was tested on latest DMD but it seems it still uses some deprecated functions. Can you please update it cus it has sparked some bitterness in the forum :smile:

https://forum.dlang.org/thread/krtoruzzqvevyawpbkjk@forum.dlang.org

**Comment by clinei** [comment]
Thanks for letting me know!
Interesting thread.

I updated GFM versions to 7.0.2 and it compiles on latest DMD.
Doesn't work on my machine with the included SDL2.dll on Windows, but might work on Linux.
Added a note to the Readme.
